// Package bus implements the Maestro message bus: routing enforcement,
// priority queuing, delivery engine, and Conductor notification surface.
//
// The bus is the coordination spine of Maestro. It owns:
//   - Routing enforcement (Conductor→Players via Assignment; Players→Conductor
//     via Done/Blocked/Background; Player→Player is always rejected).
//   - Priority queue delivery (High before Normal, FIFO within tier).
//   - Job creation on Assignment delivery (job.Service.Create).
//   - $MAESTRO_JOB_ID and $MAESTRO_SCRATCHPAD injection into Assignment payloads.
//   - Player state gating (only deliver to Idle players; queue if Running).
//   - Notification enqueueing for the Conductor.
//   - Dead-letter handling when a player transitions to Dead.
package bus

import (
	"fmt"
	"strings"

	"github.com/roanokedatasecurity/maestro/internal/job"
	"github.com/roanokedatasecurity/maestro/internal/player"
	"github.com/roanokedatasecurity/maestro/internal/store"
)

// sysFrom is the reserved sender ID for infrastructure-originated messages
// (e.g. Lifecycle events generated by the bus itself, not by a player).
const sysFrom = "maestro"

// Service is the message bus. It owns routing, delivery, and the Conductor
// notification queue. All coordination logic flows through Service — callers
// (typically the API layer) should not interact with store, player, or job
// services directly for IPC operations.
type Service struct {
	store   *store.Store
	players *player.Service
	jobs    *job.Service
}

// New constructs a Service backed by the provided store, player, and job services.
func New(s *store.Store, players *player.Service, jobs *job.Service) *Service {
	return &Service{store: s, players: players, jobs: jobs}
}

// ─── Send ──────────────────────────────────────────────────────────────────────

// Send validates routing rules, persists the message, and attempts immediate
// delivery if the target player is currently Idle. Fire-and-forget: always
// returns without waiting for the player to process the message.
//
// Routing rules (enforced):
//   - Conductor → Player:    Assignment only
//   - Player → Conductor:    Done | Blocked | Background only
//   - maestro (system) → Conductor: Lifecycle only
//   - Player → Player:       always rejected
func (svc *Service) Send(from, to string, typ store.MessageType, priority store.Priority, payload string, waitForAck bool) error {
	if err := svc.validateRouting(from, to, typ); err != nil {
		return fmt.Errorf("bus.Send: %w", err)
	}
	if _, err := svc.store.CreateMessage(from, to, typ, priority, payload, waitForAck); err != nil {
		return fmt.Errorf("bus.Send: create message: %w", err)
	}
	// Attempt immediate delivery; Deliver is a no-op if player is not Idle.
	if err := svc.Deliver(to); err != nil {
		return fmt.Errorf("bus.Send: deliver: %w", err)
	}
	return nil
}

// ─── Deliver ───────────────────────────────────────────────────────────────────

// Deliver drains the highest-priority pending message for playerID, but only if
// the player is currently Idle. If the player is Running, Dead, or the Conductor,
// Deliver is a silent no-op.
//
// On Assignment delivery:
//  1. job.Service.Create is called to create an InProgress Job with a scratchpad.
//  2. $MAESTRO_JOB_ID and $MAESTRO_SCRATCHPAD are appended to the payload.
//  3. The injected payload is persisted to the Job record.
//  4. The player is transitioned to Running.
//
// The message is marked delivered after all state transitions succeed.
func (svc *Service) Deliver(playerID string) error {
	p, err := svc.store.GetPlayer(playerID)
	if err != nil {
		return fmt.Errorf("bus.Deliver: get player: %w", err)
	}
	// Conductor notifications are surfaced via GetNotifications and rendered in the
	// notification inbox; messages are never injected into the Conductor's terminal.
	if p.IsConductor || store.PlayerStatus(p.Status) != store.PlayerStatusIdle {
		return nil
	}

	msgs, err := svc.store.ListUndelivered(playerID)
	if err != nil {
		return fmt.Errorf("bus.Deliver: list undelivered: %w", err)
	}
	if len(msgs) == 0 {
		return nil
	}

	msg := msgs[0] // ListUndelivered returns High before Normal, FIFO within tier.

	if msg.Type == store.MessageTypeAssignment {
		j, err := svc.jobs.Create(msg.ID, playerID, p.Name, msg.Payload)
		if err != nil {
			return fmt.Errorf("bus.Deliver: create job: %w", err)
		}
		injected := injectEnvVars(msg.Payload, j.ID, j.ScratchpadPath)
		if err := svc.store.SetJobPayload(j.ID, injected); err != nil {
			return fmt.Errorf("bus.Deliver: set job payload: %w", err)
		}
		if err := svc.players.Transition(playerID, player.StatusRunning); err != nil {
			return fmt.Errorf("bus.Deliver: transition player to Running: %w", err)
		}
	}

	if err := svc.store.MarkDelivered(msg.ID); err != nil {
		return fmt.Errorf("bus.Deliver: mark delivered: %w", err)
	}
	return nil
}

// ─── Signal handlers ───────────────────────────────────────────────────────────

// HandleDone processes a Done signal from a player:
//  1. Transitions Job → Complete.
//  2. Enqueues a Done notification to the Conductor.
//  3. Transitions Player → Idle.
//  4. Triggers Deliver to immediately assign the next queued work.
//
// jobID is mandatory — with multi-Job players the bus cannot infer it from playerID.
func (svc *Service) HandleDone(playerID, jobID, summary string) error {
	if jobID == "" {
		return fmt.Errorf("bus.HandleDone: jobID is required")
	}
	if err := svc.jobs.Transition(jobID, store.JobStatusComplete); err != nil {
		return fmt.Errorf("bus.HandleDone: transition job: %w", err)
	}
	jobIDPtr := jobID
	if _, err := svc.store.CreateNotification(nil, &jobIDPtr, "Done", summary); err != nil {
		return fmt.Errorf("bus.HandleDone: create notification: %w", err)
	}
	// Only transition to Idle and deliver next work if no other active Jobs remain.
	// A player may have backgrounded Jobs still in-progress; Done on one Job does
	// not free the player if others are still running.
	active, err := svc.store.ListActiveJobs(playerID)
	if err != nil {
		return fmt.Errorf("bus.HandleDone: list active jobs: %w", err)
	}
	if len(active) == 0 {
		if err := svc.players.Transition(playerID, player.StatusIdle); err != nil {
			return fmt.Errorf("bus.HandleDone: transition player to Idle: %w", err)
		}
		if err := svc.Deliver(playerID); err != nil {
			return fmt.Errorf("bus.HandleDone: deliver next: %w", err)
		}
	}
	return nil
}

// HandleBlocked processes a Blocked signal from a player. It enqueues a Blocked
// notification to the Conductor's notification queue. If wait is true, the signal
// is High-priority (surfaces as an approval overlay in the UI). The player
// remains Running — it is waiting for a decision before continuing.
//
// jobID is mandatory.
func (svc *Service) HandleBlocked(playerID, jobID, summary string, wait bool) error {
	if jobID == "" {
		return fmt.Errorf("bus.HandleBlocked: jobID is required")
	}
	// wait=true means the player is holding its HTTP request open and needs an
	// explicit approval decision before it can proceed. Surface as High priority
	// so the Conductor's notification badge fires immediately; the approval overlay
	// in the UI picks it up from there.
	priority := store.PriorityNormal
	if wait {
		priority = store.PriorityHigh
	}
	jobIDPtr := jobID
	if _, err := svc.store.CreateNotification(nil, &jobIDPtr, "Blocked", summary); err != nil {
		return fmt.Errorf("bus.HandleBlocked: create notification: %w", err)
	}
	// Enqueue a High-priority Blocked message to the Conductor's queue when wait=true
	// so the notification surface can distinguish approval-required from advisory blocked.
	if wait {
		conductors, err := svc.store.ListPlayers()
		if err != nil {
			return fmt.Errorf("bus.HandleBlocked: list players: %w", err)
		}
		for _, c := range conductors {
			if c.IsConductor {
				if _, err := svc.store.CreateMessage(sysFrom, c.ID, store.MessageTypeBlocked, priority, summary, true); err != nil {
					return fmt.Errorf("bus.HandleBlocked: create blocked message: %w", err)
				}
				break
			}
		}
	}
	return nil
}

// HandleBackground processes a Background signal from a player, indicating it is
// declaring capacity while the current Job is paused on an external dependency:
//  1. Transitions Job → Backgrounded.
//  2. Transitions Player → Idle (declaring capacity).
//  3. Triggers Deliver to immediately assign the next queued work.
//
// jobID is mandatory.
func (svc *Service) HandleBackground(playerID, jobID string) error {
	if jobID == "" {
		return fmt.Errorf("bus.HandleBackground: jobID is required")
	}
	if err := svc.jobs.Transition(jobID, store.JobStatusBackgrounded); err != nil {
		return fmt.Errorf("bus.HandleBackground: transition job to Backgrounded: %w", err)
	}
	// Background declares capacity — the player goes Idle to receive new work.
	// Check only InProgress jobs (not Backgrounded): the job we just transitioned
	// is already Backgrounded, so ListActiveJobs would include it. We only block
	// Idle transition if another job is actively running (InProgress).
	inProgress, err := svc.store.ListJobsByPlayerAndStatus(playerID, store.JobStatusInProgress)
	if err != nil {
		return fmt.Errorf("bus.HandleBackground: list in-progress jobs: %w", err)
	}
	if len(inProgress) == 0 {
		if err := svc.players.Transition(playerID, player.StatusIdle); err != nil {
			return fmt.Errorf("bus.HandleBackground: transition player to Idle: %w", err)
		}
		if err := svc.Deliver(playerID); err != nil {
			return fmt.Errorf("bus.HandleBackground: deliver next: %w", err)
		}
	}
	return nil
}

// HandlePlayerDead is called when a player's terminal process exits. It:
//  1. Marks the player Dead.
//  2. Transitions all InProgress and Backgrounded Jobs for that player to DeadLetter.
//  3. Enqueues a High-priority Lifecycle notification for each dead-letter Job so
//     the Conductor can decide whether to re-queue or discard.
func (svc *Service) HandlePlayerDead(playerID string) error {
	if err := svc.players.MarkDead(playerID); err != nil {
		return fmt.Errorf("bus.HandlePlayerDead: mark dead: %w", err)
	}

	activeJobs, err := svc.store.ListActiveJobs(playerID)
	if err != nil {
		return fmt.Errorf("bus.HandlePlayerDead: list active jobs: %w", err)
	}

	for _, j := range activeJobs {
		if err := svc.jobs.Transition(j.ID, store.JobStatusDeadLetter); err != nil {
			return fmt.Errorf("bus.HandlePlayerDead: dead-letter job %q: %w", j.ID, err)
		}
		summary := fmt.Sprintf(
			"Player %q died; job %q moved to DeadLetter (payload: %s, scratchpad: %s)",
			playerID, j.ID, j.Payload, j.ScratchpadPath,
		)
		jobIDPtr := j.ID
		if _, err := svc.store.CreateNotification(nil, &jobIDPtr, "Lifecycle", summary); err != nil {
			return fmt.Errorf("bus.HandlePlayerDead: create notification for job %q: %w", j.ID, err)
		}
	}
	return nil
}

// ─── Conductor notification surface ───────────────────────────────────────────

// GetNotifications returns unread notifications from the Conductor's queue,
// oldest first. limit=0 returns all unread notifications. offset enables
// pagination — pass 0 for the first page.
func (svc *Service) GetNotifications(limit, offset int) ([]*store.Notification, error) {
	notifs, err := svc.store.ListUnreadNotificationsPaginated(limit, offset)
	if err != nil {
		return nil, fmt.Errorf("bus.GetNotifications: %w", err)
	}
	return notifs, nil
}

// CountUnreadNotifications returns the number of unread notifications.
// Used to drive the Conductor tab badge without fetching full notification rows.
func (svc *Service) CountUnreadNotifications() (int, error) {
	count, err := svc.store.CountUnreadNotifications()
	if err != nil {
		return 0, fmt.Errorf("bus.CountUnreadNotifications: %w", err)
	}
	return count, nil
}

// MarkNotificationRead marks the given notification as read.
func (svc *Service) MarkNotificationRead(id string) error {
	if err := svc.store.MarkNotificationRead(id); err != nil {
		return fmt.Errorf("bus.MarkNotificationRead: %w", err)
	}
	return nil
}

// ─── Routing validation ────────────────────────────────────────────────────────

// validateRouting enforces the bus routing rules. Returns a descriptive error on
// any violation; nil if the message is permitted.
func (svc *Service) validateRouting(from, to string, typ store.MessageType) error {
	// Special case: "maestro" is the infrastructure sender for Lifecycle events.
	if from == sysFrom {
		if typ != store.MessageTypeLifecycle {
			return fmt.Errorf("system sender %q can only send Lifecycle messages, got %q", from, typ)
		}
		toPlayer, err := svc.store.GetPlayer(to)
		if err != nil {
			return fmt.Errorf("to player %q not found: %w", to, err)
		}
		if !toPlayer.IsConductor {
			return fmt.Errorf("Lifecycle messages must target the Conductor, got %q", to)
		}
		return nil
	}

	fromPlayer, err := svc.store.GetPlayer(from)
	if err != nil {
		return fmt.Errorf("from player %q not found: %w", from, err)
	}
	toPlayer, err := svc.store.GetPlayer(to)
	if err != nil {
		return fmt.Errorf("to player %q not found: %w", to, err)
	}

	if fromPlayer.IsConductor {
		// Conductor → self: rejected.
		if toPlayer.IsConductor {
			return fmt.Errorf("Conductor cannot send messages to itself")
		}
		// Conductor → Player: only Assignment is allowed.
		if typ != store.MessageTypeAssignment {
			return fmt.Errorf("Conductor can only send Assignment messages to players, got %q", typ)
		}
		return nil
	}

	// From a non-conductor player.
	if !toPlayer.IsConductor {
		// Player → Player: always rejected.
		return fmt.Errorf("Player-to-Player messages are not permitted (from %q to %q)", from, to)
	}
	// Player → Conductor: only Done, Blocked, Background are allowed.
	switch typ {
	case store.MessageTypeDone, store.MessageTypeBlocked, store.MessageTypeBackground:
		return nil
	case store.MessageTypeAssignment:
		return fmt.Errorf("players cannot send Assignment messages — only the Conductor can authorize work")
	default:
		return fmt.Errorf("player %q cannot send %q messages to Conductor", from, typ)
	}
}

// ─── Helpers ───────────────────────────────────────────────────────────────────

// injectEnvVars appends $MAESTRO_JOB_ID and $MAESTRO_SCRATCHPAD to an Assignment
// payload. Players reference these to emit correctly-attributed signals and to
// know where to write intermediate work.
func injectEnvVars(payload, jobID, scratchpadPath string) string {
	return strings.Join([]string{
		payload,
		"",
		"$MAESTRO_JOB_ID=" + jobID,
		"$MAESTRO_SCRATCHPAD=" + scratchpadPath,
	}, "\n")
}
